# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImageClassification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ImageClassification.proto',
  package='Farming',
  syntax='proto3',
  serialized_options=b'\n\023io.grpc.rox.FarmingB\030ImageClassificationProtoP\001\242\002\002IC',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19ImageClassification.proto\x12\x07\x46\x61rming\"\x1c\n\x0cImageRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\"\x1f\n\rImageResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2V\n\x13ImageClassification\x12?\n\x0cPredictImage\x12\x15.Farming.ImageRequest\x1a\x16.Farming.ImageResponse\"\x00\x42\x36\n\x13io.grpc.rox.FarmingB\x18ImageClassificationProtoP\x01\xa2\x02\x02ICb\x06proto3'
)




_IMAGEREQUEST = _descriptor.Descriptor(
  name='ImageRequest',
  full_name='Farming.ImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='Farming.ImageRequest.file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=66,
)


_IMAGERESPONSE = _descriptor.Descriptor(
  name='ImageResponse',
  full_name='Farming.ImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='Farming.ImageResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['ImageRequest'] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name['ImageResponse'] = _IMAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'ImageClassification_pb2'
  # @@protoc_insertion_point(class_scope:Farming.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

ImageResponse = _reflection.GeneratedProtocolMessageType('ImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGERESPONSE,
  '__module__' : 'ImageClassification_pb2'
  # @@protoc_insertion_point(class_scope:Farming.ImageResponse)
  })
_sym_db.RegisterMessage(ImageResponse)


DESCRIPTOR._options = None

_IMAGECLASSIFICATION = _descriptor.ServiceDescriptor(
  name='ImageClassification',
  full_name='Farming.ImageClassification',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=101,
  serialized_end=187,
  methods=[
  _descriptor.MethodDescriptor(
    name='PredictImage',
    full_name='Farming.ImageClassification.PredictImage',
    index=0,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_IMAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGECLASSIFICATION)

DESCRIPTOR.services_by_name['ImageClassification'] = _IMAGECLASSIFICATION

# @@protoc_insertion_point(module_scope)
