# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ImageClassification_pb2 as ImageClassification__pb2


class ImageClassificationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictImage = channel.unary_unary(
                '/Farming.ImageClassification/PredictImage',
                request_serializer=ImageClassification__pb2.ImageRequest.SerializeToString,
                response_deserializer=ImageClassification__pb2.ImageResponse.FromString,
                )


class ImageClassificationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageClassificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictImage': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictImage,
                    request_deserializer=ImageClassification__pb2.ImageRequest.FromString,
                    response_serializer=ImageClassification__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Farming.ImageClassification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageClassification(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Farming.ImageClassification/PredictImage',
            ImageClassification__pb2.ImageRequest.SerializeToString,
            ImageClassification__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
